version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev-charge
    ports:
      - "80:8000"
      - "443:8000"
    command: "gunicorn -c app/gunicorn.config.py"
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
