version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev-charge
    ports:
      - "80:8000"
      - "443:8000"
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
